name: Run build on PRs

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: true
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'tools platform-tools build-tools;35.0.0 platforms;android-35 platforms;android-31'
    - name: Build with Gradle
      run: ./gradlew build
