name: Run build on PRs

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        ache-read-only: true
    - name: Build with Gradle
      run: ./gradlew build
